spring:
  jpa:
    open-in-view: false
  batch:
    jdbc:
      isolation-level-for-create: default
      initialize-schema: always
    job:
      names: NONE
  profiles:
    active: prod
  config:
    import: secret-keys.yaml


